### ISSUE TITLE
License

### ISSUE THREAD

**Issue by 89z** [timoknapp/soundcloud-cli#19]
Please add license to enable documentation:

https://pkg.go.dev/github.com/timoknapp/soundcloud-cli/pkg/soundcloud

**Comment by 89z** [comment]
workaround:

https://godocs.io/github.com/timoknapp/soundcloud-cli

**Comment by 89z** [comment]
@timoknapp can you please reply?

**Comment by timoknapp** [comment]
Hi @89z ,
What do you exactly mean by "adding license"? Is it sufficient for you to add the "LICENSE.md" file to the repo?

Regards Timo

**Comment by 89z** [comment]
yes, something like this:

https://github.com/golang/go/blob/master/LICENSE

**Comment by timoknapp** [comment]
Okay but whats the reason behind this? So whats the benefit of having it for you?

**Comment by timoknapp** [comment]
@89z : I finally managed to add the license. Hope this helps you

**Comment by 89z** [comment]
thank you sir
