### ISSUE TITLE
Does your  soundcloud-cli app use credentials?

### ISSUE THREAD

**Issue by mediaexplorer74** [timoknapp/soundcloud-cli#43]
Hi, Timo! 
One dev question: Does your great go/golang  app use any credentials to search/listen music/download operations?
If yes, please share them. I want to create C# analog of your soundcloud-cli solution (but with simplest UI) to listen music at my old sweet Lumia950 WinPhone :)
Best wishes,
mediaexplorer
P.S. soundcloud blocked any new app registration, so I need your help...

**Comment by timoknapp** [comment]
Hi @mediaexplorer74 ,

no it does not use any credentials. It operates the same way like your browser does when not being logged in to SoundCloud. So it only uses public APIs.
And yes, SoundCloud discarded their API Key registration programm year ago unfortunately.

Btw: I build similar app just for Android TVs (like Fire TV). You can have a look to the code if you want [SoundOnFire](https://github.com/timoknapp/sound-on-fire)

Best,
Timo

**Comment by mediaexplorer74** [comment]
> Hi @mediaexplorer74 ,
> 
> no it does not use any credentials. It operates the same way like your browser does when not being logged in to SoundCloud. So it only uses public APIs. And yes, SoundCloud discarded their API Key registration programm year ago unfortunately.
> 
> Btw: I build similar app just for Android TVs (like Fire TV). You can have a look to the code if you want [SoundOnFire](https://github.com/timoknapp/sound-on-fire)
> 
> Best, Timo

Thank you for quick reply . Great answer. Ok, I understand/understood somesthing new about SoundCloud "parsing" =)  Thank you very much for your [SoundOnFire](https://github.com/timoknapp/sound-on-fire) cool sample! I 'll try to RnD it ..

Cheers up,
[M][E]
